import { useEffect, useState } from "react";
import { API } from "../config";
const steps=["ACCEPTED","PACKED","READY_TO_DISPATCH","IN_TRANSIT","ARRIVED","DELIVERED"];
const label=(s)=>String(s||"").replaceAll("_"," ");
function Orders(){
 const user=JSON.parse(localStorage.getItem("user")); const role=user?.role; const [orders,setOrders]=useState([]); const [selected,setSelected]=useState(null); const [history,setHistory]=useState([]); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
 const load=async()=>{if(!user){setLoading(false);return}try{const r=await fetch(`${API}/api/orders?role=${role}&userId=${user.id}`);const d=await r.json();if(!r.ok)throw new Error(d.message);setOrders(d);}catch(e){setMessage(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const open=async(o)=>{try{const r=await fetch(`${API}/api/orders/${o.id}`);const d=await r.json();if(!r.ok)throw new Error(d.message);setSelected(d.order);setHistory(d.history||[])}catch(e){setMessage(e.message)}};
 const move=async(status)=>{try{const r=await fetch(`${API}/api/orders/${selected.id}/status`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,actor_id:user.id,actor_role:user.role})});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessage(d.message);await open(selected);load()}catch(e){setMessage(e.message)}};
 if(!user)return <div className="demand-page"><div className="demand-card"><h1>My Orders</h1><p>Please login to view orders.</p></div></div>;
 return <div className="orders-page"><div className="orders-container"><div className="demand-header"><p className="section-label">ORDER MANAGEMENT</p><h1>{role==="BUYER"?"My Orders":"My Sales"}</h1><p>{role==="BUYER"?"Track accepted purchases, farmer contact details and shipment progress.":"Manage accepted buyer orders, preparation and dispatch status."}</p></div>{message&&<div className="demand-message-box">{message}</div>}
 {loading?<div className="empty-marketplace"><p>Loading orders...</p></div>:orders.length===0?<div className="empty-marketplace"><h2>No orders yet</h2><p>{role==="BUYER"?"Accepted farmer requests will appear here.":"Accepted buyer requests will appear here."}</p></div>:<div className="orders-grid">{orders.map(o=><div className="order-card" key={o.id} onClick={()=>open(o)}><div className="order-card-top"><span className="product-status">{label(o.status)}</span><span>{o.order_code}</span></div><h2>{o.crop_name}</h2><div className="order-main-number">{Number(o.quantity).toFixed(2)} {o.unit}<span>₹{Number(o.order_value).toFixed(2)}</span></div><div className="order-meta"><p><span>{role==="BUYER"?"Farmer":"Buyer"}</span><strong>{role==="BUYER"?o.farmer_name:o.buyer_name}</strong></p><p><span>Pickup</span><strong>{o.pickup_location}</strong></p><p><span>Deliver To</span><strong>{o.delivery_city}</strong></p><p><span>Shipment</span><strong>{o.shipment_code||"Pending grouping"}</strong></p></div><button className="interest-button">View Order</button></div>)}</div>}
 {selected&&<div className="order-detail-panel"><div className="order-detail-header"><div><p className="section-label">{selected.order_code}</p><h2>{selected.crop_name} • {Number(selected.quantity).toFixed(2)} {selected.unit}</h2></div><button className="modal-close" onClick={()=>setSelected(null)}>×</button></div><div className="order-contact-grid"><div><span>Farmer</span><strong>{selected.farmer_name}</strong><a href={`tel:${selected.farmer_account_phone||selected.farmer_phone}`}>Call Farmer: {selected.farmer_account_phone||selected.farmer_phone||"Not available"}</a></div><div><span>Buyer</span><strong>{selected.buyer_name}</strong><a href={`tel:${selected.buyer_phone||selected.buyer_account_phone}`}>Call Buyer: {selected.buyer_phone||selected.buyer_account_phone||"Not available"}</a></div><div><span>Delivery</span><strong>{selected.delivery_city}</strong><small>{selected.delivery_address}</small></div><div><span>Required Date</span><strong>{selected.required_date||"—"}</strong></div></div><div className="status-timeline">{steps.map((s,i)=>{const cur=steps.indexOf(selected.status);return <div className={`timeline-step ${i<=cur?"done":""} ${selected.status===s?"current":""}`} key={s}><span>{i<cur?"✓":i===cur?"●":"○"}</span><strong>{label(s)}</strong></div>})}</div>{role==="FARMER"&&<div className="status-actions"><button disabled={selected.status!=="ACCEPTED"} onClick={()=>move("PACKED")}>Mark Packed</button><button disabled={selected.status!=="PACKED"} onClick={()=>move("READY_TO_DISPATCH")}>Ready to Dispatch</button><button disabled={selected.status!=="READY_TO_DISPATCH"} onClick={()=>move("IN_TRANSIT")}>Start Transit</button><button disabled={selected.status!=="IN_TRANSIT"} onClick={()=>move("ARRIVED")}>Mark Arrived</button></div>}{role==="BUYER"&&<div className="status-actions"><button disabled={selected.status!=="ARRIVED"} onClick={()=>move("DELIVERED")}>Confirm Delivery</button></div>}<div className="history-list"><h3>Status History</h3>{history.map(h=><div key={h.id}><strong>{label(h.status)}</strong><span>{h.note}</span><time>{new Date(h.created_at).toLocaleString()}</time></div>)}</div>{selected.shipment_code&&<p className="small-hint">This order belongs to shipment <strong>{selected.shipment_code}</strong>. Open Smart Logistics to see the consolidated route.</p>}</div>}
 </div></div>;
}
export default Orders;
