import { useEffect, useMemo, useState } from "react";
import { API } from "../config";
const cities={mumbai:[19.076,72.8777],"navi mumbai":[19.033,73.0297],thane:[19.2183,72.9781],nashik:[20.0059,73.791],pune:[18.5204,73.8567],surat:[21.1702,72.8311],ahmedabad:[23.0225,72.5714],nagpur:[21.1458,79.0882]};
const coords=(loc)=>cities[String(loc||"").toLowerCase()]||[19.076,72.8777];
function RouteMap({route=[]}){
 const pts=route.map((p,i)=>{const [lat,lng]=coords(p.location);return {...p,x:70+(lng-72.5)*150,y:60+(24-lat)*18,i}});
 const minX=Math.min(...pts.map(p=>p.x),50),maxX=Math.max(...pts.map(p=>p.x),850),minY=Math.min(...pts.map(p=>p.y),40),maxY=Math.max(...pts.map(p=>p.y),420); const sx=(x)=>80+(x-minX)/Math.max(maxX-minX,1)*760, sy=(y)=>60+(y-minY)/Math.max(maxY-minY,1)*320;
 return <div className="route-map"><svg viewBox="0 0 900 470" role="img" aria-label="Optimized shipment route map"><defs><pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M 32 0 L 0 0 0 32" fill="none" stroke="#d9e5df" strokeWidth="1"/></pattern></defs><rect width="900" height="470" fill="#f5faf7"/><rect width="900" height="470" fill="url(#grid)" opacity="0.7"/><path d="M80 390 Q220 260 360 320 T650 180 T840 120" fill="none" stroke="#d3e3da" strokeWidth="42" strokeLinecap="round" opacity=".6"/>{pts.length>1&&<polyline points={pts.map(p=>`${sx(p.x)},${sy(p.y)}`).join(" ")} fill="none" stroke="#176b49" strokeWidth="5" strokeDasharray="10 7"/>}{pts.map((p,i)=><g key={i}><circle cx={sx(p.x)} cy={sy(p.y)} r="14" fill={p.type==="DELIVERY"?"#b42318":"#176b49"}/><circle cx={sx(p.x)} cy={sy(p.y)} r="5" fill="#fff"/><text x={sx(p.x)+18} y={sy(p.y)-8} fontSize="15" fontWeight="700" fill="#15372a">{p.location}</text><text x={sx(p.x)+18} y={sy(p.y)+12} fontSize="11" fill="#5f746b">{p.type==="DELIVERY"?"Buyer delivery":"Farmer pickup"}</text></g>)}</svg></div>
}
function SmartLogistics(){
 const user=JSON.parse(localStorage.getItem("user"));const [shipments,setShipments]=useState([]);const [selected,setSelected]=useState(null);const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
 const load=async()=>{try{const r=await fetch(`${API}/api/shipments?role=${user?.role||""}&userId=${user?.id||""}`);const d=await r.json();if(!r.ok)throw new Error(d.message);setShipments(d);if(d.length&&!selected)fetchDetail(d[0].id)}catch(e){setMessage(e.message)}finally{setLoading(false)}};
 const fetchDetail=async(id)=>{try{const r=await fetch(`${API}/api/shipments/${id}`);const d=await r.json();if(!r.ok)throw new Error(d.message);setSelected(d)}catch(e){setMessage(e.message)}};
 useEffect(()=>{load()},[]);
 const mins=selected?.summary?.estimated_minutes||0; const hours=Math.floor(mins/60), rem=mins%60;
 const routeText=selected?.route?.map(r=>r.location).join(" → ")||"—";
 return <div className="logistics-page"><div className="logistics-container"><div className="demand-header"><p className="section-label">SMART LOGISTICS</p><h1>Shared Shipments & Optimized Routes</h1><p>Accepted orders are grouped into compatible shipments, then the pickup route and shared transport cost are calculated.</p></div>{message&&<div className="demand-message-box">{message}</div>}
 {loading?<div className="empty-marketplace"><p>Loading shipments...</p></div>:shipments.length===0?<div className="empty-marketplace"><h2>No shipments yet</h2><p>Accept buyer/farmer orders first. Compatible orders can then share one vehicle.</p></div>:<>
 <div className="shipment-selector">{shipments.map(s=><button key={s.id} className={selected?.shipment?.id===s.id?"selected":""} onClick={()=>fetchDetail(s.id)}><span>{s.shipment_code}</span><strong>{s.crop_name} • {Number(s.total_quantity).toFixed(0)} KG</strong><small>{s.order_count} orders • {s.destination_city}</small></button>)}</div>
 {selected&&<><div className="shipment-hero"><div><p className="section-label">{selected.shipment.shipment_code}</p><h2>{selected.shipment.crop_name} • Consolidated Shipment</h2><p>{selected.shipment.order_count||selected.orders.length} orders • {selected.farmers.length} farmers • {selected.buyers.length} buyers</p></div><span className="shipment-status-badge">{selected.shipment.status.replaceAll("_"," ")}</span></div>
 <div className="logistics-stats"><div><span>Total Load</span><strong>{selected.summary.total_quantity} KG</strong><small>of {selected.summary.vehicle_capacity} KG capacity</small></div><div><span>Route Distance</span><strong>{selected.summary.total_distance_km} KM</strong><small>estimated road distance</small></div><div><span>Travel Time</span><strong>{hours}h {rem}m</strong><small>estimated</small></div><div><span>ETA</span><strong>{selected.summary.estimated_arrival?new Date(selected.summary.estimated_arrival).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"—"}</strong><small>{selected.summary.estimated_arrival?new Date(selected.summary.estimated_arrival).toLocaleDateString():"—"}</small></div></div>
 <div className="route-section"><div className="section-heading-row"><div><p className="section-label">ROUTE MAP</p><h2>Optimized Pickup → Delivery Route</h2><p>{routeText}</p></div></div><RouteMap route={selected.route}/></div>
 <div className="logistics-two-col"><div className="logistics-panel"><h3>Route Stops</h3>{selected.route.map((r,i)=><div className="route-stop" key={i}><div className={`route-dot ${r.type.toLowerCase()}`}>{r.stop}</div><div><strong>{r.location}</strong><span>{r.type==="PICKUP"?`${r.farmer_name} • ${r.quantity} KG`:`${r.buyer_name} • ${r.quantity} KG`}</span>{r.address&&<small>{r.address}</small>}</div></div>)}</div><div className="logistics-panel"><h3>Vehicle & Cost</h3><div className="vehicle-box"><p><span>Vehicle</span><strong>{selected.shipment.vehicle_number}</strong></p><p><span>Type</span><strong>{selected.shipment.vehicle_type}</strong></p><p><span>Driver</span><strong>{selected.shipment.driver_name}</strong></p><p><span>Driver Contact</span><strong>{selected.shipment.driver_phone}</strong></p></div><div className="cost-breakdown"><p><span>Fuel estimate</span><strong>₹{selected.summary.fuel_cost}</strong></p><p><span>Toll estimate</span><strong>₹{selected.summary.toll_estimate}</strong></p><p><span>Driver estimate</span><strong>₹{selected.summary.driver_cost}</strong></p><p><span>Loading</span><strong>₹{selected.summary.loading_cost}</strong></p><p className="total"><span>Total transport</span><strong>₹{selected.summary.total_transport_cost}</strong></p></div></div></div>
 <div className="logistics-panel"><h3>Fair Cost Allocation</h3><div className="cost-table"><div className="cost-row header"><span>Farmer</span><span>Quantity</span><span>Share</span><span>Transport Share</span></div>{selected.farmerCosts.map(f=><div className="cost-row" key={f.farmer_id}><span>{f.farmer_name}<small>{f.pickup_location}</small></span><span>{f.quantity} KG</span><span>{f.percentage}%</span><strong>₹{f.transport_share}</strong></div>)}</div></div>
 <div className="shipment-orders"><h3>Orders in This Shared Shipment</h3><div className="orders-mini-grid">{selected.orders.map(o=><div key={o.id}><span className="product-status">{o.status.replaceAll("_"," ")}</span><strong>{o.order_code}</strong><p>{o.buyer_name} • {o.quantity} KG → {o.delivery_city}</p><small>Farmer: {o.farmer_name} • Pickup: {o.pickup_location}</small></div>)}</div></div>
 </>}
 </>}
 </div></div>;
}
export default SmartLogistics;
